const routes = {
  index: '/login',
  dashboard: '/',
  signUp: '/signup',
  passwordReset: '/password/reset',
  clientprofile: '/clientprofile/',
  clientNewProfile: '/clientprofilenew',
  home: '/home',
  clientChart: '/clientchart',
  calendar: '/calendar',
  encounterNote: '/encounter_note',
  clientprofilefull: '/clientprofilefull',
  clientprofileform: '/clientprofileform',
  bulkUpload: '/bulk-upload',
  createForm: '/create_form',
  adminDashboard: '/admin-dashboard',
  createTable: '/create_table',
  createTableForm: '/createtableform',
  alterTable: '/alterTable',
  encounterTemplateNew: '/encounter-template-new',
  formBuilder: '/form_builder',
  form_builder_old: '/form_builder_old',
  preview: '/Preview',
  programDirectory: '/program-directory',
  addNewProgramDirectory: '/add-new-program-directory/',
  staffDirectory: '/staff-directory',
  tableListView: '/table-list-view',
  addNewStaffDirectory: '/add-new-staff-directory/',
  clientReferral: '/client-referral',
  master: '/master',
  createNewGroup: '/create-new-group',
  documentAdd: '/document/add',
  clientDirectory: '/client-directory',
  addEncounterDirectory: '/encounter-directory/add',
  facility: '/facility',
  department: '/department',
};

export { routes };
